name: Deploy NestJS App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 and run scripts
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # stop if any command fails

            cd /home/ubuntu/onlypark-api

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing dependencies..."
            npm install

            echo "Building app..."
            npm run build

            echo "Running migrations..."
            npm run typeorm:run-migrations

            echo "Running seeders..."
            npm run seed:run

            echo "Restarting app with PM2 and reloading env..."
            pm2 reload onlypark-api --update-env || pm2 start dist/main.js --name onlypark-api
          EOF
